import { faceMemeAvatars } from "./faceMemeAvatars";

export const LEVELS = ["Barangay", "Municipal", "Provincial", "National"];

const mockOfficialsRaw = [
  {
    id: 1,
    name: "Kapitan Alden Piattos",
    position: "Barangay Captain",
    party: "Independent",
    satisfaction: 87,
    transparency: 92,
    level: "Barangay",
    platforms: [
      "Improve barangay health center facilities",
      "Establish community daycare center",
      "Install streetlights in all purok areas",
      "Organize skills training for residents",
    ],
  },
  {
    id: 2,
    name: "Kgd. Kicki doyolabme ",
    position: "Barangay Kagawad",
    party: "Independent",
    satisfaction: 80,
    transparency: 78,
    level: "Barangay",
    platforms: [
      "Peace and order committee strengthening",
      "Free legal aid for residents",
      "Youth livelihood seminars",
      "Barangay cleanliness drives",
    ],
  },
  {
    id: 3,
    name: "Kgd. JB Batungbakal",
    position: "Barangay Kagawad",
    party: "Independent",
    satisfaction: 75,
    transparency: 81,
    level: "Barangay",
    platforms: [
      "Women and children welfare programs",
      "Senior citizen pension assistance",
      "Nutrition month activities",
      "Community health monitoring",
    ],
  },
  {
    id: 4,
    name: "SK Chair. Cris Batanglawin",
    position: "SK Chairperson",
    party: "Independent",
    satisfaction: 72,
    transparency: 76,
    level: "Barangay",
    platforms: [
      "Youth sports league organization",
      "Anti-drug awareness campaigns",
      "Student scholarship assistance",
      "Teen center establishment",
    ],
  },
  {
    id: 5,
    name: "Hon. Bucol De Gera",
    position: "City Mayor",
    party: "Partido ng Bayan",
    satisfaction: 79,
    transparency: 85,
    level: "Municipal",
    platforms: [
      "Improve city road infrastructure",
      "Expand public health services",
      "Support local businesses",
      "Enhance public safety programs",
    ],
  },
  {
    id: 6,
    name: "Hon. Jay Lourdasian",
    position: "City Vice Mayor",
    party: "Partido ng Bayan",
    satisfaction: 74,
    transparency: 80,
    level: "Municipal",
    platforms: [
      "Public market modernization",
      "Flood control masterplan",
      "Free public WiFi zones",
      "Tricycle modernization program",
    ],
  },
  {
    id: 7,
    name: "Coun. Bato Batofick",
    position: "City Councilor",
    party: "Aksyon Demokratiko",
    satisfaction: 71,
    transparency: 77,
    level: "Municipal",
    platforms: [
      "Livelihood programs for women",
      "Scholarship for deserving students",
      "Day care center expansion",
      "Anti-illegal dumping ordinance",
    ],
  },
  {
    id: 8,
    name: "Coun. Karl Biglangdapa",
    position: "City Councilor",
    party: "NPC",
    satisfaction: 68,
    transparency: 73,
    level: "Municipal",
    platforms: [
      "Business permit streamlining",
      "Night market ordinance",
      "Public cemetery improvement",
      "CCTV installation in public areas",
    ],
  },
  {
    id: 9,
    name: "Gov. Aldrin Recharge",
    position: "Provincial Governor",
    party: "Lakas-CMD",
    satisfaction: 83,
    transparency: 88,
    level: "Provincial",
    platforms: [
      "Provincial tourism development",
      "Agricultural support programs",
      "Infrastructure modernization",
      "Environmental conservation",
    ],
  },
  {
    id: 10,
    name: "Vice Gov. Dadi finily",
    position: "Provincial Vice Governor",
    party: "Lakas-CMD",
    satisfaction: 78,
    transparency: 82,
    level: "Provincial",
    platforms: [
      "Provincial hospital upgrade",
      "Rural road network expansion",
      "Farmers' cooperative support",
      "Provincial scholarship fund",
    ],
  },
  {
    id: 11,
    name: "Board Mem. Hadog kashaken",
    position: "Provincial Board Member",
    party: "NPC",
    satisfaction: 70,
    transparency: 74,
    level: "Provincial",
    platforms: [
      "Provincial disaster risk reduction",
      "Coastal resource management",
      "Fishermen livelihood assistance",
      "Provincial sports complex",
    ],
  },
  {
    id: 12,
    name: "Board Mem. Dringk Bulaga",
    position: "Provincial Board Member",
    party: "Liberal Party",
    satisfaction: 73,
    transparency: 79,
    level: "Provincial",
    platforms: [
      "Women empowerment programs",
      "Indigenous peoples welfare",
      "Provincial library network",
      "Anti-child labor ordinance",
    ],
  },
  {
    id: 13,
    name: "Sen. Goku uzumaki ",
    position: "Senator",
    party: "PDP-Laban",
    satisfaction: 91,
    transparency: 94,
    level: "National",
    platforms: [
      "Education reform bill",
      "Universal healthcare expansion",
      "Anti-corruption legislation",
      "Economic development programs",
    ],
  },
  {
    id: 14,
    name: "Sen. Tan Jairo",
    position: "Senator",
    party: "Nacionalista",
    satisfaction: 76,
    transparency: 80,
    level: "National",
    platforms: [
      "Lower electricity rates bill",
      "Mandatory coding in public schools",
      "Stricter environmental protection",
      "OFW welfare enhancement",
    ],
  },
  {
    id: 15,
    name: "Rep. Itom Youka",
    position: "House Representative",
    party: "Liberal Party",
    satisfaction: 74,
    transparency: 78,
    level: "National",
    platforms: [
      "Free internet in public schools",
      "Jeepney modernization support",
      "Mental health awareness bill",
      "Price control on basic goods",
    ],
  },
  {
    id: 16,
    name: "Rep. Its Chigo",
    position: "House Representative",
    party: "Aksyon Demokratiko",
    satisfaction: 69,
    transparency: 72,
    level: "National",
    platforms: [
      "Agricultural modernization bill",
      "Fisherfolk protection act",
      "Affordable housing program",
      "Public transport subsidy",
    ],
  },
];

const mockCandidatesRaw = [
  {
    id: 1,
    name: "Korah Cute",
    position: "Barangay Captain Candidate",
    party: "Independent",
    level: "Barangay",
    platforms: [
      "24/7 barangay tanod patrol",
      "Free medical missions monthly",
      "Community garden project",
      "Barangay CCTV installation",
    ],
  },
  {
    id: 2,
    name: "Juan Tira Dhore",
    position: "Barangay Kagawad Candidate",
    party: "Local Unity Party",
    level: "Barangay",
    platforms: [
      "Youth sports development programs",
      "Senior citizen assistance programs",
      "Community clean and green initiatives",
      "Peace and order maintenance",
    ],
  },
  {
    id: 3,
    name: "Mido Reku",
    position: "Barangay Kagawad Candidate",
    party: "Independent",
    level: "Barangay",
    platforms: [
      "Free livelihood training for mothers",
      "Daycare center improvement",
      "Nutrition feeding program",
      "Solid waste management",
    ],
  },
  {
    id: 4,
    name: "Nay Zuko",
    position: "SK Chairperson Candidate",
    party: "Independent",
    level: "Barangay",
    platforms: [
      "Free tutorial center for students",
      "Anti-drug youth campaign",
      "E-sports and tech skills training",
      "Youth leadership seminars",
    ],
  },
  {
    id: 5,
    name: "Bicotor Magtanggol",
    position: "City Councilor Candidate",
    party: "Aksyon Demokratiko",
    level: "Municipal",
    platforms: [
      "Public market renovation",
      "Livelihood programs for women",
      "Flood control projects",
      "Scholarship for deserving students",
    ],
  },
  {
    id: 6,
    name: "Bingka Diska",
    position: "City Mayor Candidate",
    party: "Liberal Party",
    level: "Municipal",
    platforms: [
      "Transparent city budget portal",
      "Free legal aid for residents",
      "Expand public transport routes",
      "Green spaces in every district",
    ],
  },
  {
    id: 7,
    name: "Isko Tamayo",
    position: "City Vice Mayor Candidate",
    party: "NPC",
    level: "Municipal",
    platforms: [
      "Night market ordinance",
      "Free business permit for micro enterprises",
      "Urban gardening program",
      "Senior citizen transport subsidy",
    ],
  },
  {
    id: 8,
    name: "Paz Pazzi",
    position: "City Councilor Candidate",
    party: "Partido ng Bayan",
    level: "Municipal",
    platforms: [
      "Mental health ordinance",
      "PWD-friendly public infrastructure",
      "Anti-illegal parking enforcement",
      "Free wi-fi in public plazas",
    ],
  },
  {
    id: 9,
    name: "Kaka chi",
    position: "Provincial Governor Candidate",
    party: "PDP-Laban",
    level: "Provincial",
    platforms: [
      "Provincial agri-tourism development",
      "Free technical-vocational training",
      "Provincial road widening project",
      "Zero hunger provincial program",
    ],
  },
  {
    id: 10,
    name: "Carla Batungbakal",
    position: "Provincial Vice Governor Candidate",
    party: "Lakas-CMD",
    level: "Provincial",
    platforms: [
      "Women and children protection office",
      "Provincial disaster response unit",
      "Organic farming initiative",
      "Rural health unit modernization",
    ],
  },
  {
    id: 11,
    name: "Bana nini",
    position: "Provincial Board Member Candidate",
    party: "Aksyon Demokratiko",
    level: "Provincial",
    platforms: [
      "Fisherfolk livelihood grants",
      "Coastal cleanup ordinance",
      "Provincial museum establishment",
      "Anti-illegal logging task force",
    ],
  },
  {
    id: 12,
    name: "Kil Luwa",
    position: "Provincial Board Member Candidate",
    party: "Independent",
    level: "Provincial",
    platforms: [
      "Provincial scholarship for top students",
      "Sports development for youth",
      "Senior citizen priority lanes",
      "Free legal aid in rural areas",
    ],
  },
  {
    id: 13,
    name: "Tan Tan",
    position: "Senator Candidate",
    party: "Nacionalista",
    level: "National",
    platforms: [
      "Lower electricity rates",
      "Mandatory coding education in public schools",
      "Stricter environmental protection laws",
      "OFW reintegration program",
    ],
  },
  {
    id: 14,
    name: "Bini Berotsa",
    position: "Senator Candidate",
    party: "Liberal Party",
    level: "National",
    platforms: [
      "Universal basic income pilot",
      "Free internet access nationwide",
      "Expanded maternity and paternity leave",
      "Mental health national program",
    ],
  },
  {
    id: 15,
    name: "Bwang Go",
    position: "House Representative Candidate",
    party: "PDP-Laban",
    level: "National",
    platforms: [
      "Affordable housing for workers",
      "Public transport modernization",
      "Anti-dynasty legislation",
      "Genuine agrarian reform",
    ],
  },
  {
    id: 16,
    name: "Jose De Bargas",
    position: "House Representative Candidate",
    party: "Aksyon Demokratiko",
    level: "National",
    platforms: [
      "Digital literacy for all ages",
      "Startup support for small businesses",
      "Climate change adaptation bill",
      "Free school supplies program",
    ],
  },
];

export const mockOfficials = mockOfficialsRaw.map((person, index) => ({
  ...person,
  image: faceMemeAvatars[index % faceMemeAvatars.length],
}));

export const mockCandidates = mockCandidatesRaw.map((person, index) => ({
  ...person,
  image: faceMemeAvatars[index % faceMemeAvatars.length],
}));

export function getOfficialById(id) {
  const numericId = Number(id);
  if (!Number.isFinite(numericId)) return null;
  return mockOfficials.find((o) => o.id === numericId) || null;
}

